### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by guicc1** [Ingenious-c0der/Superfit-Project#1]
Hi, I'm just wondering how to run this program.

**Comment by Ingenious-c0der** [comment]
Hey there, I hope you have gone through the pdf report file in the repository, it pretty much covers the entire functioning of the project. This isn't a single program but an application that needs to be hosted (remotely/cloud) in order to work.
Alternatively, if you wish to skip the server part of this project and want just the sizing program to work locally, look at the code for sizing at https://github.com/Ingenious-c0der/Superfit-Project/blob/master/users/utils.py 

We used an external point of reference in order to get real-world size metrics using an app whose source code can be found here https://github.com/Ingenious-c0der/SuperFit (only the essential files are uploaded instead of the entire Java Development kit boilerplate files for app development.)
